/**:
  ros__parameters:
    image_topic: "/camera/d455/color/image_raw"
    camera_info_topic: "/camera/d455/color/camera_info"
    image_rect_topic: "/camera/d455/color/image_rect"
    camera_info_rect_topic: "/camera/d455/color/camera_info_rect"
