/**:
  ros__parameters:
    image_topic: "~/color/image_raw"
    camera_info_topic: "~/color/camera_info"
    image_rect_topic: "~/color/image_rect"
    camera_info_rect_topic: "~/color/camera_info_rect"
